name: Build & test
on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  repository_dispatch:
    types: [ utPLSQL-build ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ORACLE_VERSION: "gvenzl/oracle-xe:18.4.0-slim"
      UTPLSQL_VERSION: "3.1.13"
      UTPLSQL_FILE: "utPLSQL"
      ORACLE_PASSWORD: oracle
      DB_URL: "127.0.0.1:1521:XE"
      DB_USER: app
      DB_PASS: app

    services:
      oracle:
        image: gvenzl/oracle-xe:18.4.0-slim
        env:
          ORACLE_PASSWORD: oracle
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --name oracle

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install utplsql
        run: sh ${{ github.workspace }}/scripts/install_utplsql.sh

      - name: Install demo project
        run: sh ${{ github.workspace }}/scripts/install_demo_project.sh

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven unit and integration tests with sonar
        run: mvn clean verify

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1.24
        if: always()
        with:
          files: target/**/TEST**.xml
